required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x:  164.5
  y: 71.5
  z: -3.5
  yaw: -180
  pitch: 0
arenas:
  0:
    world: 'world'
    x: 164.5
    y: 71.5
    z: -3.5
    yaw: -180
    pitch: 0
  1:
    world: 'world'
    x: 164.5
    y: 71.5
    z: -3.5
    yaw: -180
    pitch: 0
