required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x:  164.5
  y: 71.5
  z: -3.5
  yaw: -180
  pitch: 0
arenas:
  0:
    npc-spawn:
      world: 'world'
      x: 162.5
      y: 71
      z: -2.5
      yaw: -90
      pitch: 0
    sign:
      world: 'world'
      x: 166
      y: 72
      z: -5
    player-spawn:
      world: 'world'
      x: 155.5
      y: 69
      z: -14.5
      yaw: -180
      pitch: 0
  1:
    npc-spawn:
      world: 'world'
      x: 162
      y: 7
      z: -5
      yaw: -180
      pitch: 0
    sign:
      world: 'world'
      x: 166
      y: 72
      z: -4
    player-spawn:
      world: 'world'
      x: 155.5
      y: 69
      z: -14.5
      yaw: -180
      pitch: 0
