required-players: 2
countdown-seconds: 30
lobby-spawn:
  world: 'world'
  x:  164.5
  y: 71.5
  z: -3.5
  yaw: -180
  pitch: 0
arenas:
  0:
    world: 'world'
    spawns:
      red:
        x: 65.5
        y: -53
        z: 98.5
        yaw: 180
        pitch: 0
      blue:
        x: -84.5
        y: -53;
        z: 79.5
        yaw: -90
        pitch: 0
      green:
        x: -65.0
        y: -53
        z: 54.5
        yaw: 0
        pitch: 0
      yellow:
        x: -44.5
        y: -53
        z: 79.5
        yaw: 90
        pitch: 0
